---
#
# Script based on https://gist.github.com/emilio2hd/c910661bff37246bee17
#
- name: Check if sdkman is installed
  shell: test -d /home/{{ user.name }}/.sdkman/ && echo "yes" || echo "no"
  register: is_sdkman_installed

- name: Check if Java is installed
  command: zsh -ilc "[[ -s '/home/steimntz/.sdkman/bin/sdkman-init.sh' ]] && source '/home/steimntz/.sdkman/bin/sdkman-init.sh' &&  java -version"
  register: is_java_installed
  ignore_errors: True
  become: yes
  become_user: "{{ user.name }}"

- name: Check if Gradle is installed
  command: zsh -ilc "[[ -s '/home/steimntz/.sdkman/bin/sdkman-init.sh' ]] && source '/home/steimntz/.sdkman/bin/sdkman-init.sh' && gradle --version"
  register: is_gradle_installed
  ignore_errors: True
  become: yes
  become_user: "{{ user.name }}"

- debug:
    msg: "Failed - Java is not installed"
  when: is_java_installed is failed

- debug:
    msg: "Success - Java is installed"
  when: is_java_installed is success

- name: Download SDKMAN!
  when: is_sdkman_installed.stdout == "no"
  get_url: url={{sdkman_script_install_url}} dest=/tmp/sdkman
  become: yes
  become_user: "{{ user.name }}"

- name: Install SDKMAN!
  when: is_sdkman_installed.stdout == "no"
  script: /tmp/sdkman
  become: yes
  become_user: "{{ user.name }}"

- name: Add sdkman in .zshrc
  lineinfile: dest=/home/{{ user.name }}/.zshrc regexp="\/.sdkman/bin\/sdkman\-init\.sh" line='[[ -s "/home/{{ user.name }}/.sdkman/bin/sdkman-init.sh" ]] && source "/home/{{ user.name }}/.sdkman/bin/sdkman-init.sh"'
  become: yes
  become_user: "{{ user.name }}"

- name: Installing Gradle
  command: zsh -ilc "[[ -s '/home/steimntz/.sdkman/bin/sdkman-init.sh' ]] && source '/home/steimntz/.sdkman/bin/sdkman-init.sh' && sdk install gradle"
  become: yes
  become_user: "{{ user.name }}"
  when: is_gradle_installed is failed

- name: Installing Java 
  command: zsh -ilc "[[ -s '/home/steimntz/.sdkman/bin/sdkman-init.sh' ]] && source '/home/steimntz/.sdkman/bin/sdkman-init.sh' && sdk install java"
  become: yes
  become_user: "{{ user.name }}"
  when: is_java_installed is failed
