---
- name: Create firefox directory with right permissions
  file: path=/home/{{ user.name }}/.mozilla/xpis state=directory owner={{ user.name }} group={{ user.name }} recurse=true

- name: Download extensions
  get_url: url={{ item.url }} dest=/home/{{ user.name }}/.mozilla/xpis/{{ item.filename }}.xpi checksum=sha256:{{ item.checksum }}
  with_items:
    - "{{ firefox.extensions }}"

- name: Install Unzip
  pacman: name=unzip state=present

- name: Create temp folder
  file: path=/tmp/ffextensions/{{ item.filename }} state=directory owner={{ user.name }} group={{ user.name }} recurse=true
  with_items:
    - "{{ firefox.extensions }}"

- name: Unarchive extensions
  unarchive:
    src: /home/{{ user.name }}/.mozilla/xpis/{{ item.filename }}.xpi
    dest: /tmp/ffextensions/{{ item.filename }}
  with_items:
    - "{{ firefox.extensions }}"

- name: Install extensions
  shell : |
    FFPROFILE=$(grep -oP 'Path=\K[\w.-]+' /home/saxetz/.mozilla/firefox/profiles.ini | head -1)
    EXTENSION=$(cat /tmp/ffextensions/{{ item.filename }}/install.rdf | grep -Po '({[\w\d-]*})')
    mv /home/{{ user.name }}/.mozilla/xpis/{{ item.filename }}.xpi /home/{{ user.name }}/.mozilla/firefox/$FFPROFILE/extensions/$EXTENSION.xpi 
    chown -R {{ user.name }}:{{ user.name }}  /home/{{ user.name }}/.mozilla/firefox/$FFPROFILE/extensions/
  with_items:
    - "{{ firefox.extensions }}"
