---

- hosts: localhost
  roles:
          #    - { role: sudo, tags: ['sudo'] }
          #    - { role: docker, tags: ['docker'] }
          #    - { role: zprezto }
          #    - { role: vim }
    - { role: xmonad }
