syntax on
set nocompatible
filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'mattn/emmet-vim'
Plugin 'tomasr/molokai'
Plugin 'jremmen/vim-ripgrep'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'wakatime/vim-wakatime'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'sheerun/vim-polyglot'
" CoC
Plugin 'neoclide/coc.nvim', {'branch': 'release'}
Plugin 'elixir-lsp/coc-elixir', {'do': 'yarn install && yarn prepack'}
call vundle#end()
filetype plugin indent on

"""""""""""""""""""""""""""""""""
" Bindings
"""""""""""""""""""""""""""""""""

" source Vim configuration file and install plugins
nnoremap <silent><leader>1 :source ~/.vimrc \| :BundleInstall<CR>

nmap <leader>f :Rg<SPACE>
nmap <leader>p :NERDTreeToggle<CR>

"\o | \O to insert a line below / above and return to normal mode
nmap <leader>o o<esc>
nmap <leader>O O<esc>

" map k/j to next/prev tab
nmap <S-k> gt
nmap <S-j> gT

" remove highlighted search
nmap <leader><space> :nohl<cr>

" CoC
"
"   extensions
let g:coc_global_extensions = ['coc-tsserver', 'coc-angular', 'coc-elixir', 'coc-java']

"   remap keys for applying codeAction to the current line.
nmap <leader>ac  <Plug>(coc-codeaction)

"   apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

"   goTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

"   tool tip documentation and diagnostics
nnoremap <silent> K :call CocAction('doHover')<CR>

"   navegate into error
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

"   rename coc
nmap <leader>rn <Plug>(coc-rename)

"   Directory management
nnoremap <Leader>m :CocCommand explorer <cr>

"   Refactoring
nnoremap <Leader>r :CocCommand document.renameCurrentWord <cr>

"   ctrl p
nmap <space>f :CtrlP<CR>

"""""""""""""""""""""""""""""""""
" Basic Configuration
"""""""""""""""""""""""""""""""""
set novb                " no bells please
set showmode
set ignorecase
set smartcase           " Case insensitive search with lowercase terms, sensitive with uppercase
set hlsearch            " highlight search results
set gdefault            " default to global substitution, without having to put the /g at the end
set relativenumber      " show relative line numbers
set number              " but show the current linenum at the center

if &diff
    colorscheme molokai
endif
