local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>e", ":NvimTreeToggle<CR>")
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Find files" })
vim.keymap.set("n", "<leader>fg", builtin.git_files, { desc = "Find git files" })
vim.keymap.set("n", "<leader>fl", builtin.live_grep, { desc = "Live grep" })
vim.keymap.set("n", "gd", builtin.lsp_definitions, { desc = "Go to definition" })
vim.keymap.set("n", "gr", builtin.lsp_references, { desc = "Go to references" })
vim.keymap.set("n", "gi", builtin.lsp_implementations, { desc = "Go to implementations" })
vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Hover docs" })
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, { desc = "Rename symbol" })
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "Code action" })
vim.keymap.set("n", "<leader>ci", function()
  vim.lsp.buf.code_action({
    apply = true,
    context = { only = { "quickfix" } },
  })
end, { desc = "Quick import" })
vim.keymap.set("n", "<leader>ce", vim.diagnostic.open_float, { desc = "Show error" })
vim.keymap.set("n", "]d", vim.diagnostic.goto_next, { desc = "Next error" })
vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, { desc = "Prev error" })
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "All errors" })
