---
- name: Install sudo
  pacman: name=sudo state=present

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes

- name: Create a new ssh key
  user:
    name: '{{ user.name }}'
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: yes
  become_user: '{{ user.name }}'

- name: Copy sudo configuration
  template: src=sudoers.j2 dest=/etc/sudoers mode=440 validate='visudo -cf %s'
