---
- name: Install Docker.
  pacman: name=docker state=present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- include: docker-compose.yml
