---
- name: Install Vim and dependencies
  pacman:
    pkg: 
      - vim
      - the_silver_searcher
    state: present
  when: ansible_os_family == "Archlinux"

- name: Install Vim and dependencies
  debug:
    msg: Nothing here yet {{ansible_os_family}}
  when: ansible_os_family == "Darwin"

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: Create .vim directory with permission
  file: path={{home.directory}}/{{ user.name }}/.vim state=directory owner={{ user.name }} recurse=true

- name: Create Vundle.vim directory with permission
  file: path={{home.directory}}/{{ user.name }}/.vim/bundle/Vundle.vim state=directory owner={{ user.name }} recurse=true

- name: Git clone Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{home.directory}}/{{ user.name }}/.vim/bundle/Vundle.vim"

- name: Configure .vimrc
  template: src="vimrc" dest="{{home.directory}}/{{ user.name }}/.vimrc" owner={{ user.name }}

- name: Run PluginInstall
  shell: vim +PluginInstall +qall

- name: Run PluginClean
  shell: vim '+PluginClean!' +qall
