---
- name: Install Vim and dependencies
  pacman:
    pkg: 
      - vim
      - the_silver_searcher
    state: present

- name: Create Vundle.vim directory with permission
  file: path=/home/{{ user.name }}/.vim/bundle/Vundle.vim state=directory owner={{ user.name }} recurse=true

- name: Git clone Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/home/{{ user.name }}/.vim/bundle/Vundle.vim"
    force: yes
    update: no
  become: yes
  become_user: "{{ user.name }}"

- name: Configure .vimrc
  template: src="vimrc" dest="/home/{{ user.name }}//.vimrc" owner={{ user.name }} group={{ user.name }}

- name: Run PluginInstall
  shell: echo | echo | vim +PluginInstall +qall &>/dev/null 
  become: yes
  become_user: "{{ user.name }}"

- name: Run Yarn install
  shell: yarn install chdir="/home/{{ user.name }}/.vim/bundle/coc.nvim"
  become: yes
  become_user: "{{ user.name }}"

- name: Run PluginClean
  shell: echo | echo | vim '+PluginClean!' +qall &>/dev/null 
  become: yes
  become_user: "{{ user.name }}"

- name: Add NodeJS latest version as current version
  shell: asdf set nodejs 18.4.0 chdir="/home/{{ user.name }}.vim/bundle/coc.nvim"
  become: yes
  become_user: "{{ user.name }}"
