---
- name: Install Vim and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - the_silver_searcher

- name: Create .vim directory with permission
  file: path=/home/{{ user.name }}/.vim state=directory owner={{ user.name }} recurse=true

- name: Create Vundle.vim directory with permission
  file: path=/home/{{ user.name }}/.vim/bundle/Vundle.vim state=directory owner={{ user.name }} recurse=true

- name: Git clone Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/home/{{ user.name }}/.vim/bundle/Vundle.vim"

- name: Configure .vimrc
  template: src=".vimrc" dest="/home/{{ user.name }}/.vimrc" owner={{ user.name }}

- name: Run PluginInstall
  shell: vim +PluginInstall +qall

- name: Run PluginClean
  shell: vim '+PluginClean!' +qall
