---
- name: install Xorg Server.
  pacman: name=xorg-server state=present

- name: install Xorg Xinit.
  pacman: name=xorg-xinit state=present

- name: make directory /home/{{ user.name }}/screenshots
  file: name=/home/{{ user.name }}/screenshots state=directory owner={{ user.name }}

- name: install driver
  pacman: name={{ item }} state=present
  with_items:
    - "[{{ computer.gpu  }}]"

- name: install XMonad
  pacman: 
    pkg:
      - xmonad
      - xmobar
      - xmonad-contrib
    state: present

- name: install XMonad dependecies.
  pacman: name=rofi state=present

- name: create .xmonad directory with user permission
  file: path=/home/{{ user.name }}/.xmonad/lib/Config state=directory owner={{ user.name }} recurse=true

- name: copy my screensaver config
  template: src=xscreensaver dest=/home/{{ user.name }}/.xscreensaver owner={{ user.name }}

- name: copy my idea vim config
  template: src=ideavimrc dest=/home/{{ user.name }}/.ideavimrc owner={{ user.name }}

- name: copy my xmonad main file
  template: src=xmonad.hs dest=/home/{{ user.name }}/.xmonad/xmonad.hs owner={{ user.name }}

- name: create my xmonad configurations directory with user permission
  file: path=/home/{{ user.name }}/.xmonad/lib/Config state=directory owner={{ user.name }} recurse=true

- name: copy my xmonad configurations
  template: src={{ item }} dest=/home/{{ user.name }}/.xmonad/lib/{{ item }} owner={{ user.name }}
  with_items:
    - Config/Mappings.hs
    - Config/Layout.hs
    - Config/ManageHook.hs
    - Config/StartUpHooks.hs

- name: Copy my xinitrc
  template: src=xinitrc dest=/home/{{ user.name }}/.xinitrc owner={{ user.name }}

- name: Copy my xmobar
  template: src=xmobar dest=/home/{{ user.name }}/.xmobarrc owner={{ user.name }}

- name: compile XMonad
  shell: xmonad --recompile
  become: yes
  become_user: "{{ user.name }}"
