---
- name: Install Xorg Server.
  pacman: name=xorg-server state=present

- name: Install Xorg Xinit.
  pacman: name=xorg-xinit state=present

- name: Make directory /home/{{ user.name }}/aur
  file: name=/home/{{ user.name }}/aur state=directory owner={{ user.name }}

- name: Install cower.
  makepkg: name=cower user={{ user.name }} skip_pgp=true
  become: yes
  become_user: "{{ user.name }}"

- name: Install pacaur.
  makepkg: name=pacaur user={{ user.name }}
 
- name: Install driver
  pacman: name={{ item }} state=present
  with_items:
    - "{{ computer.gpu  }}"

- name: Install XMonad
  pacman: name={{ item }} state=present
  with_items:
    - xmonad
    - xmonad-contrib

- name: Install XMonad dependecies.
  pacman: name={{ item }} state=present
  with_items:
    - rofi

- name: Create .xmonad directory with user permission
  file: path=/home/{{ user.name }}/.xmonad state=directory owner={{ user.name }} recurse=true

- name: Copy xmonad configurations
  template: src=xmonad.hs dest=/home/{{ user.name }}/.xmonad/xmonad.hs owner={{ user.name }}

- name: Copy xmonad configurations
  template: src=xinitrc dest=/home/{{ user.name }}/.xinitrc owner={{ user.name }}


- name: Compile XMonad
  shell: xmonad --recompile
  become: yes
  become_user: "{{ user.name }}"
