---
- name: Install Xorg Server.
  pacman: name=xorg-server state=present

- name: Install Xorg Xinit.
  pacman: name=xorg-xinit state=present

- name: Make directory /home/{{ user.name }}/aur
  file: name=/home/{{ user.name }}/aur state=directory owner={{ user.name }}

- name: Install cower.
  makepkg: name=cower user={{ user.name }} skip_pgp=true
  become: yes
  become_user: "{{ user.name }}"

- name: Install pacaur.
  makepkg: name=pacaur user={{ user.name }}
 
- name: Install driver
  pacman: name={{ item }} state=present
  with_items:
    - "{{ computer.gpu  }}"

- name: Install XMonad
  pacman: name={{ item }} state=present
  with_items:
    - xmonad
    - xmonad-contrib
