---
- name: Install Xorg Server.
  pacman: name=xorg-server state=present

- name: Install Xorg Xinit.
  pacman: name=xorg-xinit state=present

- name: Make directory /home/{{ user.name }}/aur
  file: name=/home/{{ user.name }}/aur state=directory owner={{ user.name }}

- name: Install driver
  pacman: name={{ item }} state=present
  with_items:
    - "[{{ computer.gpu  }}]"

- name: Install XMonad
  pacman: 
    pkg:
      - xmonad
      - xmonad-contrib
    state: present

- name: Install XMonad dependecies.
  pacman: name=rofi state=present

- name: Create .xmonad directory with user permission
  file: path=/home/{{ user.name }}/.xmonad/lib/Config state=directory owner={{ user.name }} recurse=true

- name: Copy my xmonad main file
  template: src=xmonad.hs dest=/home/{{ user.name }}/.xmonad/xmonad.hs owner={{ user.name }}

- name: Create my xmonad configurations directory with user permission
  file: path=/home/{{ user.name }}/.xmonad/lib/Config state=directory owner={{ user.name }} recurse=true

- name: Copy my xmonad configurations
  template: src={{ item }} dest=/home/{{ user.name }}/.xmonad/lib/{{ item }} owner={{ user.name }}
  with_items:
    - Config/Mappings.hs
    - Config/Layout.hs

- name: Copy my xinitrc
  template: src=xinitrc dest=/home/{{ user.name }}/.xinitrc owner={{ user.name }}

- name: Compile XMonad
  shell: xmonad --recompile
  become: yes
  become_user: "{{ user.name }}"
