#!/usr/bin/env bash

pkgs=$(checkupdates 2>/dev/null | wc -l)

if [ "$pkgs" -eq 0 ]; then  
    class="uptodate"  
    icon=""
    pkgs=""  
else  
    class="update"  
    icon=""
fi  

result="{\"text\":\""$pkgs"\",\"alt\":\""$icon"\",\"class\":\""$class"\"}"
echo -e $result
