# This script is based on https://www.reddit.com/r/archlinux/comments/5r5ep8/make_your_arch_fonts_beautiful_easily/
---
- name: Disable embedded bitmap for all fonts, enable sub-pixel RGB rendering, and enable the LCD filter which is designed to reduce colour fringing when subpixel rendering is used.
  file:
    src: '/etc/fonts/conf.avail/{{ item }}'
    dest: '/etc/fonts/conf.d/{{item}}'
    state: link
  with_items:
    - '70-no-bitmaps.conf'
    - '10-sub-pixel-rgb.conf'
    - '11-lcdfilter-default.conf'
- name: Enable FreeType subpixel hinting mode
  replace:
    path: /etc/profile.d/freetype2.sh
    regexp: '^#(export FREETYPE_PROPERTIES.*)$'
    replace: '\1'

- name: Create fonts directory
  file:
    path: /home/{{ user.name }}/.local/share/fonts/
    owner: "{{user.name}}"
    group: "{{user.name}}"
    recurse: true
    state: directory

- name: Get DejaVu Sans Mono Nerd Font Complete Mono
  get_url:
    url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/fa69496f5a3291fbcb6c0ad5bcec9c8bcab842fc/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /home/{{ user.name }}/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono.ttf owner={{user.name}} group={{user.name}}
    checksum: sha256:0be1bb4ae68562c29566da73c1562af11dd381705bac4ff9870be666b5856b5d

- name: Get DejaVu Sans Mono Nerd Font Complete Mono Bold
  get_url:
    url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/5371994aa892fcd4eed149c63d905d6815b36a38/patched-fonts/DejaVuSansMono/Bold/complete/DejaVu%20Sans%20Mono%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /home/{{ user.name }}/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono Bold.ttf owner={{user.name}} group={{user.name}}

- name: Get DejaVu Sans Mono Nerd Font Complete Mono Oblique
  get_url:
    url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/5371994aa892fcd4eed149c63d905d6815b36a38/patched-fonts/DejaVuSansMono/Italic/complete/DejaVu%20Sans%20Mono%20Oblique%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /home/{{ user.name }}/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono Oblique.ttf owner={{user.name}} group={{user.name}}

- name: Get DejaVu Sans Mono Nerd Font Complete Mono Bold Oblique
  get_url:
    url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/5371994aa892fcd4eed149c63d905d6815b36a38/patched-fonts/DejaVuSansMono/Bold-Italic/complete/DejaVu%20Sans%20Mono%20Bold%20Oblique%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /home/{{ user.name }}/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono Bold Oblique.ttf owner={{user.name}} group={{user.name}}

- name: Update font-cache
  command: fc-cache -fv
  become: yes
  become_user: "{{ user.name }}"
